export const WARNING_CODES = {
    REINDEX_UNNECESSARY_IGNORE_ONLY: 'REINDEX_UNNECESSARY_IGNORE_ONLY',
    REINDEX_PREFLIGHT_UNKNOWN: 'REINDEX_PREFLIGHT_UNKNOWN',
    IGNORE_POLICY_PROBE_FAILED: 'IGNORE_POLICY_PROBE_FAILED',
    FILTER_MUST_UNSATISFIED: 'FILTER_MUST_UNSATISFIED',
    MUST_NOT_SATISFIED_WITHIN_RETRIEVAL_BUDGET: 'MUST_NOT_SATISFIED_WITHIN_RETRIEVAL_BUDGET',
    MUST_RESULTS_MAY_BE_INCOMPLETE_WITHIN_RETRIEVAL_BUDGET: 'MUST_RESULTS_MAY_BE_INCOMPLETE_WITHIN_RETRIEVAL_BUDGET',
    MUST_CONJUNCTIVE_RETRIEVAL_UNAVAILABLE: 'MUST_CONJUNCTIVE_RETRIEVAL_UNAVAILABLE',
    MUST_CONJUNCTIVE_RETRIEVAL_FAILED: 'MUST_CONJUNCTIVE_RETRIEVAL_FAILED',
    RERANKER_FAILED: 'RERANKER_FAILED',
    RERANKER_INPUT_DEGRADED: 'RERANKER_INPUT_DEGRADED',
    RERANKER_SKIPPED_INPUT: 'RERANKER_SKIPPED_INPUT',
    SEARCH_DIRTY_WORKTREE_NOT_SYNCED: 'SEARCH_DIRTY_WORKTREE_NOT_SYNCED',
    SEARCH_DIRTY_FILE_EVIDENCE_UNAVAILABLE: 'SEARCH_DIRTY_FILE_EVIDENCE_UNAVAILABLE',
    SEARCH_CHANGED_FILES_BOOST_SKIPPED: 'SEARCH_CHANGED_FILES_BOOST_SKIPPED',
    SOURCE_FRESHNESS_CHECKPOINT_UNAVAILABLE: 'SOURCE_FRESHNESS_CHECKPOINT_UNAVAILABLE',
    SOURCE_FRESHNESS_UNVERIFIED: 'SOURCE_FRESHNESS_UNVERIFIED',
    SOURCE_CHANGES_PENDING: 'SOURCE_CHANGES_PENDING',
    SEARCH_INVALID_GROUP_TARGET_OMITTED: 'SEARCH_INVALID_GROUP_TARGET_OMITTED',
    SEARCH_RESULT_SET_NOT_CACHE_ADMISSIBLE: 'SEARCH_RESULT_SET_NOT_CACHE_ADMISSIBLE',
    SEARCH_RESULT_INDEX_NOT_ADMISSIBLE: 'SEARCH_RESULT_INDEX_NOT_ADMISSIBLE',
    NAVIGATION_REPAIR_REQUIRED: 'NAVIGATION_REPAIR_REQUIRED',
} as const;

export type WarningCode = typeof WARNING_CODES[keyof typeof WARNING_CODES];

export const WARNING_CODE_SET: ReadonlySet<WarningCode> = new Set<WarningCode>(Object.values(WARNING_CODES));

export function isWarningCode(value: unknown): value is WarningCode {
    return typeof value === 'string' && WARNING_CODE_SET.has(value as WarningCode);
}
